name: Generate Image

on:
  push:
    paths:
      - "screens/**"

  schedule:
    # Run every day at 12:00 UTC
    - cron: "0 0,12 * * *"

  # Lets you manually run it from GitHub
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Get your repository files
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install Pillow/etc.
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run your Python program
      - name: Generate image
        run: python generate.py

      # Prepare GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Deploy everything in screens/ to GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./screens"

      # Deploy it
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

